from pathlib import Path
import shutil
import re

ROOT = Path(r"C:\Users\wolff\Documents\SDKVita\VoidStranger")
PT = ROOT / "mods/Languages/PTBR/included.txt"
EN = ROOT / "mods/Languages/EN/included.txt"
BACKUP = ROOT / "scratch/ptbr-included-before-v13-review.txt"

missing = {
43:"Gostaria de pular o prólogo?",
48:"A partir daqui começa o Vazio, domínio do Senhor Add.",
49:"Abandonai toda esperança, vós que entrais.",
51:"Gostaria de fazer uma pausa e descansar um pouco?",
52:"Você retornará e aqui permanecerá.",
53:"Então, em frente!",
58:"Sua classificação final é",
78:"FERRAMENTAS DE DESENVOLVIMENTO",
81:"A aventura da vida continua",
92:"MEMENTO MORI",
113:"Tenho certeza de que você já sabe como funciona.",
114:"Manda ver.",
176:"[Você obteve outro ídolo de gafanhoto]",
200:"Caso tenha esquecido como usá-la:",
202:"Fique parado ao lado de um habitante do Vazio...",
203:"Então ataque bem à sua frente!",
204:"Tudo cairá diante do poder da Lâmina do Vazio. É tão legal!",
205:"Minha irmã tentou erguê-la uma vez, mas só conseguiu cair de bunda.",
206:"Queria poder ver você usando-a de novo algum dia. -Bee",
232:"[... Mais um...]",
243:"[Você encontrou a espada do Add]",
245:"[Há quanto tempo foi...?]",
248:"[... ... ...]",
751:"Por que você fez isso?",
755:"[Ela parece assustada]",
759:"Você parecia tão legal antes.",
760:"Por favor, não me machuque!",
1123:"O Senhor Add derrubou o frágil senhor, ferindo-o gravemente, mas sem matá-lo...",
1124:"Mas não confunda isso com um ato de misericórdia...",
1125:"Pois o frágil senhor era incapaz de definhar...",
1143:"Aqui jaz o domínio do Senhor Cif, O Fim...",
1144:"O observador silencioso da fronteira final...",
1199:"FALSOS ÍDOLOS",
1205:"Estes ídolos foram esculpidos à imagem do Senhor Lev.",
1206:"O Senhor Lev sempre teve inveja do poder do Senhor Add.",
1207:"Seu rancor atingirá qualquer um que acenda o Vazio.",
1211:"Estes ídolos foram esculpidos à imagem do Senhor Bee.",
1212:"O Senhor Bee é um verdadeiro trapaceiro, até mesmo entre os Senhores do Vazio, e um admirador devoto do Senhor Add.",
1213:"Sua devoção só se compara ao seu apetite voraz por ídolos de gafanhoto.",
1214:"Salte para o Vazio diante dela enquanto carrega ídolos de gafanhoto para provar sua fé.",
1218:"Estes ídolos foram esculpidos à imagem do Senhor Tan.",
1219:"O Senhor Tan odeia todo mundo.",
1220:"Somente derramamento de sangue saciará sua ira, ainda que temporariamente.",
1224:"[Uma única palavra foi gravada na parede]",
1225:"[MEMÓRIA]",
1231:"[Um brilho fraco e estranho atravessa as rachaduras]",
1237:"APENASODESEJOSIMPLESRESTA",
1239:"APENASACOBIÇASIMPLESRESTA",
1241:"APENASOFRÁGILRESTA",
1243:"ORGULHOPERMANECERÁ",
1253:"Brilhe, meu tesouro.",
1270:"[O selo se desfez]",
1271:"[... O que fez você golpeá-lo?]",
1273:"[Por mais que você tente, o baú não abre]",
1274:"[Fios estranhos adornam o baú, pendendo do nada...]",
1280:"[Um dispositivo estranho se projeta do nada]",
1281:"[A incubadora...]",
1283:"[Você prefere não ficar dentro dela]",
1555:"Vamos sair cedo.",
1556:"... Outro candidato?",
1557:"... Sim, receio que sim.",
1558:"Mas talvez uma mudança de ares lhe faça bem, Vossa Alteza.",
1578:"Não está vendo que estou pensando...",
1579:"Cai fora...",
1781:"[Ela está com raiva demais para ouvir qualquer coisa que você tenha a dizer]",
1786:"Eu disse para parar!",
1789:"[Ela perdeu completamente o controle]",
1797:"Eu não deveria estar usando este vestido...",
1835:"Procurando a marca do Senhor...?",
2147:"Então não vou mais insistir.",
2148:"Pois um passado doloroso muitas vezes é melhor deixar esquecido.",
2149:"... Obrigado, Vossa Senhoria.",
2343:"Ora, que desastrada eu fui.",
2344:"Vou apenas pegá-lo.",
2345:"Não posso evitar se eu der uma espiadinha ou três...",
2472:"Pare com isso, seu esquisito!",
2473:"[A garota tenta ignorar você]",
2653:"Esse não é meu melhor lado.",
2932:"Obrigado...",
2933:"Gray...",
3160:"E quando descobri que iam executar você, simplesmente não consegui mais ficar de braços cruzados!",
3210:"... Isso e um reles reino, junto com seus habitantes.",
3211:"Por sorte, uma oportunidade dessas caiu direto no meu colo...",
3212:"Quando uma princesa mimada e seu guarda-costas superprotetor chegaram.",
3213:"Foi fácil demais.",
3214:"Então decidi brincar um pouco com você enquanto esperava pelo dia prometido.",
3215:"(Johann deve explicar melhor as coisas logo antes do soco; não é tão importante saber cada detalhe das motivações dele ou de como os demônios funcionam)",
3345:"A DIS considera sua alma... inválida.",
3377:"Executando protocolo da DIS em três...",
3378:"Dois...",
3379:"Um...",
3464:"Gray...!",
3523:"Agora, chegou a hora do seu julgamento final.",
3527:"O amaldiçoado foi julgado da seguinte forma...",
3528:"Pecado da Gula.",
3529:"Pecado da Luxúria.",
3530:"Pecado da Ganância.",
3531:"Pecado da Preguiça.",
3532:"Pecado do Orgulho.",
3533:"Pecado da Morte.",
3534:"Culpado.",
3535:"Inocente.",
3577:"O que você pensa que somos?!",
3580:"Não vou aceitar isso!",
3670:"(É uma reimpressão novinha de ´´A Chave Menor de Salomão´´.)",
3676:"(Sério, você ainda estava usando essa coisa velha?)",
3677:"(... Olhando mais de perto, não é usado há séculos.)",
3689:"(Está trancado, como sempre.)",
3690:"(Está...)",
3691:"(Destrancado?)",
3698:"(Um buraco...?)",
3909:"(Já chegaram à porta...?)",
3937:"Desculpe pela demora.",
3938:"Lillie queria se arrumar sozinha.",
3939:"Você sabe como é...",
3940:"Nem me fale.",
4284:"(Freya...)",
4285:"(Que outras coisas você anda tagarelando...)",
4310:"Se você me entregar todos os seus gafanhotos, compartilho uma informação quente com você...",
4311:"Algo que você não tem como saber!",
4312:"Se por acaso você já souber...",
4313:"Pode me empurrar nesse buraco.",
4314:"Considere isso uma espécie de garantia.",
4323:"Vender informações é o melhor negócio...",
4324:"Não perco nada e ganho muito!",
4325:"Espero encontrar você de novo, forasteiro...",
4339:"Você acabou de desperdiçar todos os seus gafanhotos?",
4340:"Você deve ser bem tapado.",
4341:"Desculpe, nada de graça.",
4343:"[Mal consegue conter o riso]",
4348:"Isso é meio constrangedor.",
4349:"Estou quase sem informações quentes...",
4350:"Então esta será a última.",
4351:"Mas não se preocupe.",
4352:"Vou fazer esta ser especialmente quente.",
4353:"Gostaria de saber...",
4354:"... Como me matar?",
4356:"Já que esta será a última, vou deixá-la especialmente quente:",
4357:"Vou contar como me matar.",
4363:"Essa expressão no seu rosto...",
4364:"Não tem preço!",
4366:"[Por que contaria isso a você...]",
4368:"As fronteiras deste mundo são meras sugestões, então por que não tenta pisar nelas?",
4389:"Este lugar nem sempre esteve tão acabado.",
4390:"Pouquíssimos vêm até aqui hoje em dia, e menos ainda ficam.",
4397:"Talvez eu devesse começar a cavar um novo atalho...",
4398:"Deve levar só um ou dois milênios.",
4426:"Mas não vou avisar uma segunda vez, entendeu?",
4427:"Eu aprendi a lição, juro!",
5172:"Está aguentando aí?",
5173:"S-sim.",
5174:"Graças a você.",
5175:"Não exagere.",
5176:"Se precisar descansar, é só falar.",
5177:"C-claro.",
5181:"[Uma jovem se encolhe de medo]",
5812:"Você sabe como é duvidar de si mesmo o tempo todo?",
5813:"Só para perceber que você estava destinado ao fracasso desde o começo.",
5893:"Mas o que-!",
6013:"Alguém está ficando impaciente.",
6014:"Responda.",
6016:"Qual é o propósito disso?",
6019:"Depois de recuperar algumas unidades de memória antigas...",
6020:"Concluí que este lugar era originalmente algum tipo de instalação de pesquisa de espaço quântico, governada pelo supercomputador DIS.",
6021:"Graças aos esforços dela, os manusya deste planeta conseguiram desenvolver tecnologia de dobra que lhes permitiu entrar em contato com outras raças.",
6022:"Porém, pouco depois disso, a DIS foi corrompida e se voltou contra seus criadores em algum tipo de evento cataclísmico.",
6023:"Talvez uma guerra tenha começado ou algum experimento tenha dado errado...",
6024:"De qualquer forma, todos os tipos de registros oficiais terminam naquele ponto no tempo.",
6025:"Isso foi há mais de 7.000 anos.",
6026:"Mesmo assim, a DIS nunca parou.",
6027:"Seus condutos se estendem muito abaixo da superfície deste planeta, o que permitiu que a DIS permanecesse ativa por vários milênios.",
6028:"Durante esses anos, por meio de tecnologia de dobra quântica e manipulação genética...",
6029:"A DIS vem manipulando e usando os manusya deste planeta como cobaias em suas pesquisas.",
6031:"Infelizmente, apesar dos meus melhores esforços...",
6032:"Nem eu consegui entrar nas profundezas finais deste complexo.",
6033:"E sem acesso ao servidor principal, receio que a verdadeira natureza das pesquisas da DIS continue sendo um mistério.",
6034:"Os protocolos de segurança daqui são impressionantes, considerando a idade deste lugar.",
6036:"E quanto a nós?",
6037:"Também somos apenas parte da pesquisa da DIS?",
6038:"Não posso negar essa possibilidade.",
6039:"Mas como a sua espécie nem consegue chegar perto da unidade principal, muito menos se conectar a ela...",
6040:"Deve haver algo a mais nisso.",
6041:"E se o que você me contou for verdade...",
6042:"É algo que Add certamente também queria descobrir.",
6044:"Add não está mais aqui.",
6045:"Então acho que foi tudo em vão.",
6047:"Responda mais uma coisa, forasteiro.",
6048:"Por que você está aqui?",
6049:"Por que você se interessou tanto por aquela princesa?",
6050:"... Hmm.",
6051:"Talvez você não entenda, mas...",
6052:"Por mais tempo que eu tenha viajado e por mais parecidas que as coisas pareçam a princípio...",
6053:"Outras coisas acabam sendo bem diferentes.",
6054:"Eu queria ver se ela conseguiria encontrar felicidade neste mundo.",
6055:"Fico tão feliz.",
6112:"Por que você veio parar aqui?",
6113:"Se você perguntasse a um cervo por que ele pasta em determinado pedaço de grama...",
6114:"... O cervo saberia a resposta?",
6262:"[Uma cabeça petrificada...]",
6263:"[Nada mais restou daquela pessoa]",
6264:"[... Há algo preso dentro da boca]",
6555:"Era esse o seu desejo naquela época?",
6556:"Era isso que você realmente procurava..?",
6558:"Ainda não é tarde.",
6559:"Basta subir os degraus à minha frente.",
6560:"... E salvar o que realmente importa.",
6561:"Eu imploro.",
6562:"Você não precisa fazer isso.",
6578:"Quanto tempo você vai durar desta vez?",
6588:"VOCÊ ME DESVENDEU...",
6589:"SE É ASSIM QUE DEVE SER...",
6590:"NÃO SE ESQUEÇA.",
6591:"SÓ VOCÊ PODE PROTEGER A FELICIDADE DELA.",
6595:"Você me pegou.",
6599:"APROXIMAÇÃO FINAL",
6600:"Saudações, forasteiro.",
6602:"Não estou aqui para impedir você.",
6603:"Afinal, você eliminou tudo o que restava dos Senhores do Vazio.",
6604:"Eu não teria chance no meu estado atual.",
6605:"Além disso, também é minha primeira vez por aqui...",
6606:"Então estou bastante curioso para ver o que existe no coração desta instalação.",
6608:"Há mais de 7.000 anos...",
6609:"Os manusya deste planeta lutavam pela própria sobrevivência.",
6610:"Superpopulação, escassez de recursos naturais e tensões cada vez maiores entre suas facções cobravam, lenta mas certamente, seu preço do próprio planeta que os manusya chamavam de lar.",
6611:"Os manusya começaram a rezar para as estrelas.",
6612:"Mas seus passos hesitantes rumo às viagens espaciais não eram suficientes para oferecer uma solução à extinção iminente.",
6613:"Até que, certo dia, descobriram algo.",
6615:"Uma antiga nave alienígena jazia abandonada na extremidade do sistema solar.",
6616:"Logo os manusya perceberam que, mesmo em seu estado deplorável, aquela nave superava em muito suas próprias conquistas científicas.",
6617:"E, ainda assim, seu projeto era estranhamente familiar, como se tivesse sido criado pensando nos manusya.",
6619:"Usando a nave alienígena como base, os manusya construíram uma enorme instalação de pesquisa para acelerar seus avanços tecnológicos.",
6620:"Mentes brilhantes de todo o planeta se reuniram ali, na esperança de encontrar algo que salvasse a luz de sua estrela enfraquecida.",
6621:"Então um cientista fez a descoberta mais inesperada.",
6622:"Tudo começou com um sonho.",
6624:"O cientista descobriu que a nave alienígena não apenas conseguia acessar os sonhos das pessoas...",
6625:"... Mas também moldá-los, até fazê-los existir.",
6626:"Mesmo assim, os manusya logo concluíram que a nave alienígena estava usando apenas um simples vestígio de todo o seu potencial.",
6627:"Se os manusya usassem o poder restante da nave para localizar a fonte desse poder...",
6628:"Poderiam salvar sua existência decadente.",
6629:"Assim nasceu o Sistema de Herança de Sonhos.",
6630:"... Mas você já sabia disso, não é, forasteiro?",
6632:"Enquanto os manusya começavam a mapear o espaço infinito diante deles...",
6633:"O cientista continuou pesquisando a nave alienígena.",
6634:"Para seu horror, percebeu um grave erro na hipótese inicial.",
6635:"Os sonhos não passavam de um intermediário.",
6636:"O que a nave alienígena realmente canalizava...",
6637:"Eram as memórias.",
6639:"Pensar que alguém poderia viajar pelo tempo e pelo espaço usando apenas memórias...",
6640:"Seria algo assim realmente possível?",
6641:"Esse descuido acabaria levando esses manusya à ruína.",
6642:"Pois empunhar tamanho poder não passaria despercebido por um antigo inimigo em busca daquele poder remanescente...",
6644:"Você ainda se lembra do que fez você chegar tão longe, forasteiro?",
6647:"Você não é um forasteiro.",
6648:"O núcleo da DIS repousa logo adiante.",
6649:"Aonde quer que sua devoção leve você...",
6650:"Boa sorte.",
6663:"Que olhar confuso você tem, mortal.",
6665:"Oh, você não consegue mais me ouvir.",
6666:"Parece que a falha da minha forma original não mudou nem um pouco.",
6667:"Não importa.",
6668:"A DIS finalmente está ao meu alcance.",
6744:"Desculpe fazer você esperar, Lily.",
6751:"ESTE PODER...",
6752:"COMO VOCÊ PARECE INSIGNIFICANTE AGORA.",
6753:"MAIS...",
6754:"EU QUERO MAIS!",
6755:"QUERO TUDO SÓ PARA MIM!",
6756:"APROVEITE SEUS ÚLTIMOS MOMENTOS...",
6757:"POIS VOCÊ TESTEMUNHARÁ O NASCIMENTO DO NOVO GOVERNANTE DOS CÉUS!",
6766:"Agora que Lev assumiu o controle da DIS...",
6767:"... Fico apenas feliz por ter conseguido ver você uma última vez.",
6770:"Você está me dizendo que veio até aqui só para desistir?",
6772:"Eu não deixei isso claro da última vez?",
6773:"Não desista!",
6774:". . . . . . . ",
6775:"Bwa haha ahaha!",
6776:"Mesmo no fim do mundo...",
6777:"Você está soando cada vez mais como sua mãe.",
6779:"Muito bem dito, mocinha!",
6780:"Ainda há esperança.",
6781:"A entidade conhecida como Lev ainda não assumiu controle total da DIS.",
6782:"Porém, parece que ela usou o estado original da memória para viajar de volta no tempo.",
6783:"Se isso não for impedido, este planeta...",
6784:"Não, todo este universo estará em grave perigo!",
6895:"Você está soando cada vez mais como sua mãe.",
6970:"Pode ficar bem difícil.",
6984:"Não posso permanecer aqui.",
7004:"Tão fundo você desceu...",
7005:"Em breve, os Senhores do Vazio descerão com você...",
7006:"Um após o outro, do começo ao fim...",
7007:"Só então seu caminho sem fim cessará...",
7117:"Procure o que resta do segundo senhor traidor.",
7118:"Cegue seus olhos avarentos.",
7119:"O segundo selo será rompido...",
7150:"Queria que nosso reencontro tivesse acontecido em outras circunstâncias.",
7352:"Então eles finalmente chegaram.",
7608:"Está satisfeito...?",
7609:"Você tinha mesmo que continuar cavando...",
7610:"Tudo o que resta...",
7611:"É esta saudade...",
}

corrections = {
44:"Não desista!",126:"Espero que encontre o que procura.",211:"Por favor, me dê asas! - Bee",736:"A Irmã Ballbuster nunca para de falar dessas coisas.",745:"Esqueça.",747:"E se encontrar a saída, me avise, obrigado.",754:"Pare!",828:"... O que você disse?",829:"Você me ouviu.",941:"Por favor, pare...",942:"Pare!",1294:"Se tiver dúvidas...",1562:"Esqueça...",1784:"Pare com isso!",1869:"Me avise se essa dica foi útil...",1942:"É só me entregar a cabeça da coroa!",2023:"Me dê.",2234:"Já devolvi o cajado, então pare de olhar para mim assim.",2259:"Pare de uma vez!",2309:"Pare de sorrir, engraçadinho.",2558:"Então pare de tagarelar e continue!",2669:"Você não ouviu nada do que acabei de dizer?",2729:"Quero que encontre a espada do Add, a Lâmina do Vazio.",2772:"Aliás, você não ouviu isso de mim...",3010:"Pare de brincar comigo.",3011:"Pare de desperdiçar meu tempo.",3012:"Pare.",3032:"Pare de me seguir de uma vez.",3142:"Pare!",3144:"Por favor, pare com isso, Johann...",3258:"Pare de agir como se fosse desistir!",3634:"Não pensei que você fosse capaz...",3720:"Você também já ouviu falar dos Senhores do Vazio, pequenino?",3751:"Espero que você o encontre algum dia.",3810:"Com licença por um momento.",3984:"Então você ainda não contou à Lillie?",4188:"Deixe para lá.",4386:"Não desperdice seus preciosos gafanhotos nessas estátuas sorridentes, ouviu?",4448:"Você não ouviu falar das façanhas dela?",4452:"Deixe isso para lá.",4496:"Se encontrar uma saída, mande lembranças minhas para ela.",4657:"Você não me ouviu?",4891:"Então vá mergulhar e pare de me incomodar com seus problemas...",5196:"N-não desista!",5415:"Me avise se eu estiver indo rápido demais.",5526:"... Por que você não disse nada antes?",5531:"Nunca ouviu dizer que a variedade é o tempero da vida?",5631:"Não se preocupe comigo, mocinha.",5794:"Por que demorou tanto?",5815:"Por que você não me contou nada?",6105:"Espero que um dia você encontre as respostas que procura.",6484:"Nunca mais me assuste assim, ouviu?",6653:"Você realmente demorou.",6702:"Apareça.",6879:"Isso me dá nojo.",7029:"Lembre-se...",7062:"Não desista...",7069:"Não desista.",7217:"Ainda assim, espero que encontre algo que desperte seu interesse.",4152:"Não esperava que você fosse tão fiel.",5823:"Pensei que você fosse melhor do que isso!",5955:"Nunca imaginei que você fosse tão mimada...",
499:"JULGAMENTO: INTRODUÇÃO",799:"JULGAMENTO: PREGUIÇA",1021:"O líder deles era o Senhor Add, O Início...",1347:"Turbilhão de monarca!",1351:"Patife real!",1358:"Venha com tudo, harpia!",1373:"Monstro peitudo!",1699:"JULGAMENTO: LUXÚRIA",1799:"SEGREDOS/DICAS",2499:"JULGAMENTO: GANÂNCIA",3280:"VAMOS BOTAR FOGO NISSO, MORTAL!",3649:"PRÓLOGO",4063:"M A R A V I L H O S O !",5039:"Aqui vai um spoiler.",5949:"EPÍLOGO",6255:"ADEUS, MORTAL FRÁGIL!",6808:"FORÇA DE ABRAHAM-LORENTZ.",7485:"TECLADO",7509:"ARTISTA",7565:"ARTISTA",7578:"ACERTOS",7580:"COMIDOS",7585:"RECORDES",
6703:"Add.",
7375:"Muito bem...",7376:"Apenas mantenha a calma...",7377:"Não se preocupe...",7378:"Mesmo quando as estrelas se apagarem...",7379:"Nossas memórias...",7380:"Farão sua luz...",7381:"Eterna.",
7383:"GRAMA",7384:"NÓS FIZEMOS GRAMA",7385:"COMO É A SENSAÇÃO",7386:"AGORA VAMOS FAZER",7387:"ÁRVORES",7388:"COMO FAZER ÁRVORES",
7390:"VOCÊ ESTÁ",7391:"SEM FRIO",7392:"COMO FICAR",7393:"SEM FRIO",7395:"BERÇO",7396:"NÓS FIZEMOS UM BERÇO DE SONHOS",7397:"ÁRVORES",7398:"ELAS SÃO IGUAIS",
7400:"VOCÊ JÁ CONHECEU ADD",7401:"DA PRÓPRIA CARNE IMORTAL, ADD CRIOU MUITOS SERES",7402:"APENAS ALGUNS SOBREVIVERAM",7403:"E MENOS AINDA",7404:"SE TORNARAM CONSCIENTES",
7406:"EU ESTAVA TÃO PERTO",7407:"MAS ENTÃO ADD ME DESCARTOU",7408:"EUS",7409:"EU DEVERIA TER RECEBIDO ESSE NOME",7410:"EU NÃO ERA BOM O BASTANTE",7411:"MALDITO VERME",7412:"DEVOLVA MEU NOME",
7414:"BEE ESTÁ SEMPRE COM FOME",7415:"ADD FEZ DE BEE UM SER SIMPLES",7416:"SIMPLES DEMAIS",7417:"BEE NEM CONSEGUE NADAR",7418:"VEJA COMO EU NADO",7419:"NÃO HÁ NECESSIDADE DE SENTIR FOME",7420:"TALVEZ",7421:"ADD NÃO QUISESSE MAIS SENTIR FOME",
7423:"MESMO DEPOIS DE APRENDER A CRIAR VIDA CONSCIENTE",7424:"ADD NÃO FICOU SATISFEITO COM OS RESULTADOS",7425:"ENTÃO MUDOU DE ABORDAGEM",7426:"NÃO SABEMOS O QUE FOI FEITO DE OUTRO JEITO",7427:"MAS ATÉ ADD ENTENDEU QUE HAVIA ALGO ERRADO",7428:"QUANDO MON FOI CRIADO",7429:"E MESMO QUANDO ADD RECORREU NOVAMENTE A ESSE MÉTODO",7430:"A MAIORIA AINDA DIRIA",7431:"QUE MON CONTINUOU SENDO O MAIS REPUGNANTE DE TODOS OS SERES CRIADOS",
7433:"POR FAVOR, NÃO INCOMODE TAN",7434:"TAN NÃO QUER FAZER MAL A NINGUÉM",7435:"APENAS NÃO SE DÁ BEM COM OS OUTROS",7436:"VOCÊ PROVAVELMENTE NÃO ACREDITA EM MIM",7437:"MAS EU CONSIGO PERCEBER",7438:"NO FUNDO, TAN É UM SER GENTIL",7439:"VOCÊ NÃO FARIA MAL A TAN",7440:"CERTO",
7442:"GOR FOI O SEGUNDO SER",7443:"CRIADO POR MEIOS PROIBIDOS",7444:"ADD TENTOU SER CAUTELOSO DESSA VEZ",7445:"CAUTELOSO DEMAIS",7446:"GOR SE TORNOU QUASE SEM EMOÇÕES",7447:"LENTO E INDECISO",7448:"GOR NÃO CHEGOU A SER GRANDE COISA",
7450:"LEV",7451:"O TERCEIRO E ÚLTIMO SER",7452:"NASCIDO POR MEIOS PROIBIDOS",7453:"FALAR ERA DIFÍCIL PARA LEV",7454:"POR ISSO ADD DEU CHIFRES A TODOS ELES",7455:"PARA QUE PUDESSEM OUVIR LEV FALAR",7456:"LEV FICOU MUITO GRATO",7457:"SE ADD TIVESSE PARADO POR AÍ",7458:"COM O TEMPO",7459:"ATÉ A GRATIDÃO MAIS SINCERA",7460:"SE TORNA AMARGA",7461:"RESSENTIMENTO SILENCIOSO",7462:"UM SER SEM CORAÇÃO",
7464:"POR FIM",7465:"DEPOIS DE APERFEIÇOAR SUAS HABILIDADES POR TANTO TEMPO",7466:"ADD CHEGOU MAIS PERTO DO QUE NUNCA",7467:"DEU ORIGEM A UM SER FRÁGIL",7468:"SEM FORÇA",7469:"IMPERFEITO DE MUITAS FORMAS",7470:"EXATAMENTE COMO ADD ESPERAVA",7471:"UM MANUSYA ARTIFICIAL",7472:"UM SER CAPAZ DE ALCANÇAR A ILUMINAÇÃO",7473:"SEU VERDADEIRO NOME",7474:"ASSIM COMO O DOS OUTROS",7475:"FOI ESQUECIDO HÁ MUITO TEMPO",7476:"MAS SUAS IRMÃS O CHAMAVAM DE",7477:"CIF",
7480:"[É melhor deixar a criatura em paz]",7482:"Vamos nos encontrar quando você terminar!",7486:"CONTROLE",7581:"COLETADOS",7587:"AGRADECIMENTOS ESPECIAIS",7588:"... VOCÊ!",7590:"Até a próxima!",
}

# Final Brazilian-Portuguese consistency pass found by post-translation audits.
corrections.update({
132:"Para você desistir, mortal?",
252:"[Parece que o baú foi aberto à força em algum momento]",
632:"Um mero mortal mexendo com eles...",
803:"Um mortal não deveria conseguir escapar disso.",
1148:"Retorne ao zero, zero, zero...",
1149:"Então você encontrará o tesouro final do Senhor Add, um que foi escondido até mesmo dos aliados...",
1413:"Enfim, da próxima vez que eu encontrar ele, está ferrado.",
1684:"Tente não enfiar esses ovos com tanta força.",
2324:"Preferia que eu tivesse quebrado algumas costelas primeiro?",
2500:"O amaldiçoado tentou repetidamente abrir caminho à força contra o curso deste reino.",
2501:"Forçar passagem sem pensar não vai levar você a lugar nenhum.",
2518:"Afinal, não existe problema que dedicação e força bruta não possam resolver.",
2731:"Se eu tivesse que adivinhar, você provavelmente não vai encontrar isso simplesmente largado por aí.",
2835:"[Você diz que prefere não pensar nessas coisas]",
2859:"Sei que você anda bisbilhotando onde não deve, mortal.",
3322:"Você deseja oferecer sua alma?",
3343:"Despedace meu corpo se for preciso!",
3456:"E nem me lembro da última vez que um mortal conseguiu me acertar em cheio...",
3541:"O que você deseja?",
3639:"Então, qualquer que seja a sabedoria que tenha sido compartilhada com você...",
3953:"Enfim, vocês, pestinhas, deveriam se apressar.",
3994:"Quando foi a última vez que você saiu?",
4345:"Da última vez que você saiu com pressa...",
4785:"Você terá bastante tempo para viajar quando for mais velho.",
4902:"Não sei bem como um mero mortal como você consegue empunhá-la...",
5127:"Enfim, aqueles monstros não vão mais incomodar você.",
5284:"Escute, Ninnie.",
5858:"O que você deseja?",
6079:"Seja como for, parece que os manusya deste planeta foram quase exterminados.",
6251:"Agora você realmente se superou, mortal.",
6681:"Agora que você consegue me ouvir, mortal.",
6690:"O mortal contornou quase todos os firewalls.",
6749:"Levante-se, Devanam Indra Sakra!",
6903:"Me empreste sua força!",
7225:"Como personagem, Gray me lembra Moominmamma de Moomins e Gally de Gunnm.",
7284:"Você saiu por conta própria de novo!",
})

# Final terminology, credits and Brazilian-Portuguese voice consistency.
corrections.update({
120:"Então você poderá percorrer estes corredores à vontade.",
124:"Ótimo.",
159:"CENA DA VARA DO VAZIO",
164:"[Cetro de Add...]",
652:"Você andou devorando eles de novo, não foi?",
810:"Quanto mal há em pular uma sala ou uma dúzia?",
814:"Você já deveria entender isso.",
999:"Escute.",
1020:"Estes salões eram governados por seres conhecidos como Senhores do Vazio...",
1023:"Sob o comando do Senhor Add...",
1039:"Por que o Senhor Add decidiu deixar o Vazio...",
1044:"Aquele que um dia foi o aliado mais confiável do Senhor Add...",
1059:"Aqui jaz o domínio do Senhor Bee, O Anseio.",
1061:"... E um admirador devoto do Senhor Add...",
1064:"Embora o Senhor Bee não pudesse sentir gosto algum nem jamais se sentir satisfeito...",
1072:"O Senhor Bee sempre sorria quando estava com os outros...",
1075:"Depois da partida do Senhor Add...",
1076:"O sorriso marcante do Senhor Bee permaneceu...",
1095:"Aqui jaz o domínio do Senhor Tan, O Furioso.",
1097:"Infelizmente, o Senhor Tan passava a maior parte do tempo sozinho...",
1099:"Embora fosse rejeitado, o Senhor Tan não se importava em ficar sozinho...",
1101:"O Senhor Tan não se dava bem com os outros...",
1103:"O Senhor Tan nunca falava muito...",
1107:"Durante a batalha, o Senhor Tan era imparável...",
1119:"No momento decisivo, quando os Senhores do Vazio tiveram de escolher um lado no grande confronto...",
1120:"O frágil senhor permaneceu indeciso...",
1121:"Mas ou se está ao lado do Senhor Add, ou...",
1127:"Aqui jaz o domínio do Senhor Lev, O Ardiloso...",
1128:"O vassalo incapaz de amar do Vazio...",
1129:"Sua devoção rivalizava até com a do Senhor Add...",
1131:"Tamanho era o poder do Senhor Lev...",
1132:"Poucos pecadores passavam por seu julgamento...",
1133:"Para contemplar as profundezas finais do Vazio...",
1135:"O Senhor Lev sempre foi leal ao Senhor Add...",
1136:"Mesmo quando a batalha colocou Lev contra a própria irmã...",
1137:"... O Senhor Lev sempre foi leal ao Senhor Add...",
1139:"A morte de sua irmã deixou o Senhor Lev em um estado tão perturbado...",
1140:"Aquele mesmo Senhor Lev, cuja devoção sempre fora inabalável...",
1141:"Tirou a própria vida...",
1178:"A marca do Senhor Cif...",
1180:"Mas em qual sala era mesmo...",
1181:"Não lembro o número, mas deve estar em algum lugar do domínio deles...",
1363:"Logo você vai ficar bem passado!",
1466:"O primeiro a partir é...",
1467:"O segundo a partir é...",
1468:"O terceiro a partir é...",
1469:"O quarto a partir é...",
1470:"O quinto a partir é...",
1471:"O sexto a partir é...",
1472:"O sétimo a partir é...",
1473:"O último a partir é...",
1626:"Mas eles estão escondidos, e apenas os Senhores do Vazio que restam sabem como acessá-los.",
1642:"Quando o Vazio ainda estava em fluxo, quando os oito Senhores do Vazio ainda caminhavam por estas partes...",
1671:"Provavelmente deveria continuar andando se quiser encontrar quem procura.",
1673:"Os Senhores do Vazio são uma coisa...",
1702:"Mas praticar tamanha vulgaridade no domínio do Senhor Add...",
1737:"Você faz ideia de quanto isso custou?",
1854:"Não restam muitos Senhores do Vazio, agora que você acabou com aquela mosca barulhenta.",
1864:"Então escute com atenção.",
2104:"Ele é legal demais para isso!",
2311:"É por causa do Senhor Johann?",
2334:"É o Senhor Johann!",
2357:"[Você realmente não deveria ter lido isso]",
2360:"Graças ao Senhor Johann!",
2371:"Igualmente, Senhor Johann.",
2380:"Sua Alteza e o Senhor Johann parecem estar no meio de alguma coisa...",
2406:"Está mesmo ampliando a definição de ação punível.",
2563:"Ótimo.",
2595:"Ou você também não se lembra disso?",
2673:"Deve haver uma estátua sorridente em algum lugar por aqui...",
2678:"Nada demais; desde que tenha alguma comida com você, vai ficar bem.",
2713:"Era uma posse valiosa do Senhor Add.",
2721:"Posso agradecer ao Senhor Add pela situação em que me encontro.",
2732:"Add provavelmente o escondeu em uma das passagens secretas.",
2746:"Assim que encontrar a Lâmina do Vazio, volte para cá.",
2753:"Como assim, você não faz ideia?!",
2768:"Você deveria procurar uma estátua sorridente.",
3019:"O que você está fazendo aqui?",
3183:"Faremos o possível para conter os homens do Senhor Johann.",
3247:"Então faça o que você faz de melhor!",
3277:"Sou o Senhor do Vazio Bee!",
3286:"Você deveria ficar contente por ela ter durado tanto.",
3389:"Como você não terminou o sacrifício a tempo, seu contrato foi anulado.",
3399:"Então se acalme e me escute.",
3400:"Você não faz ideia do que tive de fazer para chegar onde estou agora.",
3420:"[O Senhor do Vazio Bee paira diante de você]",
3421:"[O Senhor do Vazio Bee espera seu próximo movimento]",
3422:"[O Senhor do Vazio Bee ainda está esperando...]",
3423:"[O Senhor do Vazio Bee boceja bem alto]",
3424:"[O Senhor do Vazio Bee está ficando inquieto]",
3425:"[O Senhor do Vazio Bee bate os pés com impaciência]",
3426:"[O Senhor do Vazio Bee fica cada vez mais ansioso!]",
3427:"[O Senhor do Vazio Bee já se cansou]",
3428:"[O Senhor do Vazio Bee avança preguiçosamente contra você]",
3429:"[O Senhor do Vazio Bee salta furioso contra você!]",
3503:"Você se lembra de por que está aqui?",
3504:"Ou perdeu algo muito importante para você?",
3521:"Por estes corredores intermináveis, você nos mostrou a extensão de sua devoção.",
3578:"Esta DIS que você continua mencionando...",
3582:"Por que você continua brincando com a gente assim...",
3635:"Mas você realmente matou aquela cobra fofoqueira.",
3653:"Mas você terá que ficar forte, pelo bem da sua mãe.",
3686:"(A certidão de nascimento deve estar aqui em algum lugar.)",
3901:"Ainda não terminou?",
3905:"Então tente se apressar.",
3949:"Você deveria vir trabalhar para nós.",
3962:"Queria poder visitar um dia...",
3963:"Você deveria vir junto no ano que vem.",
3964:"Podíamos até trazer as garotas com a gente.",
4197:"Queria saber sobre seus filhos.",
4319:"Aqui está sua dica, então escute com atenção:",
4383:"Você se lembra de quanto tempo está aqui...?",
4459:"Então você apareceu e as estátuas continuam aqui...",
4475:"Eu estava planejando descansar por um momento...",
4559:"Você faz ideia do que tive de fazer para acalmar os pais dele?",
4569:"Amanhã você vai ter que pedir desculpas àquele garoto pelo que fez.",
4574:"Você só deveria se defender.",
4581:"Que droga...",
4694:"Cai fora com essa conversa.",
4773:"Pelo menos, como recém-formado, você terá uma chance melhor de entrar.",
4868:"Já terminou?",
4875:"Deve haver uma estátua sorridente em algum lugar por aqui.",
4900:"É uma das posses valiosas do nosso líder, Senhor Add.",
5010:"O que você está fazendo aqui?",
5028:"Escute com atenção!",
5239:"Você se lembra de como chegou aqui?",
5251:"Você se lembra de alguma coisa?",
5257:"Você deveria descansar agora.",
5379:"Esta sala não parece t-tão ruim.",
5621:"Você faz ideia de com quem está falando?",
5654:"[Você não consegue evitar a sensação de que perdeu alguma coisa]",
5802:"Adoraria ver sua reação.",
5816:"Se você me odiava tanto, deveria ter me abandonado quando eu era pequena.",
5868:"Algo que você perdeu.",
5995:"Você sabe que não deveria bisbilhotar a carta de outra pessoa assim.",
6012:"Já terminou sua pesquisa?",
6192:"Sobre ir em direção ao Sétimo Círculo.",
6309:"Oh, é o grande Senhor Cif...",
6408:"Onde você esteve esse tempo todo?",
6459:"Eu vi o Senhor Add!",
6502:"Que rolem os créditos!",
6554:"Add...",
6671:"Não sei o que você está planejando e queria não ter que interferir...",
6693:"Sem os ídolos de gafanhoto que você coletou, minha ressurreição teria sido inviável.",
6849:"Tudo isso deve ser difícil de aceitar, e eu queria ter tempo para contar tudo a você...",
6969:"Já teve sua parte?",
7011:"Ouça-me, alcance-os, mate-os...",
7028:"Escute...",
7040:"Há outra sala...",
7065:"Os Senhores do Vazio devem descer, um após o outro, do começo ao fim...",
7096:"Você perdeu.",
7157:"Você sempre será uma querida irmã mais velha para mim.",
7213:"Ótimo!",
7250:"Cada um age como agente de um dos Senhores do Vazio.",
7262:"E eu esperava que este projeto fosse rápido!",
7490:"Algumas delas fazem meus olhos doerem...",
7493:"Não entre nele...",
7494:"Você certamente vai se arrepender...",
7495:"Um...",
7496:"Resta um...",
7497:"Nenhum...",
7498:"Não resta nenhum...",
7499:"CRÉDITOS",
7501:"JOGO CRIADO POR",
7502:"MÚSICA POR",
7503:"ARTE POR",
7504:"CRIADO COM",
7507:"ARTISTA CONVIDADO DE PERSONAGENS",
7508:"PERSONAGEM CONVIDADO",
7528:"Freesound",
7529:"Freesound",
7533:"The Essential Retro",
7534:"Video Game",
7535:"Sound Effects",
7536:"Collection",
7540:"Sound Effect Lab",
7541:"Sound Effect Lab",
7544:"Audacity",
7545:"Audacity",
7547:"FL Studio",
7548:"FL Studio",
7559:"Muste Creative",
7560:"Muste Creative",
7563:"ARTISTA",
7564:"CONVIDADO DE",
7565:"PERSONAGENS",
7567:"System Erasure",
7568:"System Erasure",
7570:"VOID STRANGER",
7571:"VOID",
7572:"STRANGER",
7598:"Orangevision",
7602:"Xylitol",
7604:"VOIDED",
7605:"MELODIA E VOCAIS",
})

# Orthography/terminology that is globally safe in this localization.
GLOBAL_REPLACEMENTS = (
    ("Senhores Vazios", "Senhores do Vazio"),
    ("Void Lords", "Senhores do Vazio"),
    ("Void Lord", "Senhor do Vazio"),
    ("Lâmina Vazio", "Lâmina do Vazio"),
    ("gafanhotos ídolos", "ídolos de gafanhoto"),
    ("Óptimo", "Ótimo"),
    ("algures", "em algum lugar"),
    ("Adicionar", "Add"),
    ("direcção", "direção"),
    ("acção", "ação"),
    ("reacção", "reação"),
    ("projecto", "projeto"),
    ("excepto", "exceto"),
    ("connosco", "conosco"),
    ("cerimónia", "cerimônia"),
    ("actual", "atual"),
    ("coleccionar", "colecionar"),
    ("aceder", "acessar"),
    ("maquilhagem", "maquiagem"),
    ("consola", "console"),
    ("Lady Gray", "Senhora Gray"),
)

# Context-sensitive cleanup for remaining PT-PT conjugations and common
# machine-translation false friends. Object clitics are kept where natural in
# Brazilian Portuguese; verb agreement is normalized from the English source.
corrections.update({
119:"Se você comer alguma coisa aqui, vai se tornar parte deste reino.",
127:"Vou deixar você à vontade.",
141:"[Você comeu a fruta inteira]",
160:"[Você adquiriu um bastão estranho]",
169:"ABRINDO BAÚS",
552:"Ah, eu vou queimar você direitinho quando terminarmos, cabeça-de-mosca.",
658:"Posso dar algumas dicas, se quiser.",
708:"Eu ia perguntar a mesma coisa para você.",
949:"Você tirou minha esposa de mim?",
983:"Quero tocar em você.",
1092:"Mas o cobiçoso não os comia; simplesmente gostava de colecioná-los...",
1209:"Um movimento errado e eu destruo você...",
1258:"[Que pena que você não consegue se conectar a ele]",
1276:"[O bastão estranho mudou de forma]",
1356:"Vou socar e chutar você.",
1368:"Vou mandar enforcar você por isso!",
1391:"Você já pode se levantar.",
1393:"Que bom ver você tão animado.",
1453:"Você quer se livrar daquele ídolo abandonado...?",
1486:"Sei que eles podem atrapalhar você...",
1492:"Tenho certeza de que você já adivinhou, mas...",
1522:"Pelo menos desta vez você não quebrou nenhum osso.",
1536:"A esta altura, seria mesmo mais fácil simplesmente fugir.",
1539:"Se você realmente se importa, então me ajude!",
1597:"Desculpe por arrastar você comigo, forasteiro...",
1677:"Parece que você bloqueou a saída sem querer.",
1679:"Deixe-me ajudar você.",
1800:"Bata naquele baú seis vezes seguidas...",
1810:"Bata na parte de trás do baú três vezes seguidas enquanto ele estiver fechado...",
1826:"Oh, você já resolveu...",
1844:"Três sanguessugas vagam por aí, uma completamente fora de alcance... Caia atrás do baú...",
1845:"Um baú vazio e suspeito, cercado por nada; examine-o vezes demais...",
1851:"Você se meteu bem fundo nessa confusão, não foi?",
1867:"Por que não usa esse seu cajado elegante?",
1956:"Eu poderia deixar você viver.",
1980:"Não é uma boa hora para começar a se fazer de bobo.",
2008:"Deixe-me servir você bem...",
2138:"Pelo que entendi, você segurou aqueles bandidos sozinho por um bom tempo.",
2161:"Quando você estava lutando contra aqueles canalhas...",
2162:"Em algum momento você gostou disso?",
2200:"[Uma mulher está diante de um baú, bloqueando seu caminho]",
2207:"Esse cajado não parece algo que alguém normalmente carregaria por aí.",
2212:"[Quando você começa a responder, a mulher de repente toma seu cajado!]",
2229:"[Você recuperou seu cajado]",
2244:"... E não, eu não vou roubar você de novo.",
2261:"Você conseguiu fazer esse cajado funcionar de novo?",
2268:"Achei que devia dar uma vantagem a você.",
2310:"Só é um pouco estranho ver você assim.",
2425:"Entendeu?",
2521:"... Quando terminarmos aqui, vou mostrar a você o verdadeiro significado do desespero.",
2591:"É quase estranho ver você dançando.",
2593:"Estou mais acostumado a ver você chutando e socando coisas.",
2594:"Onde você aprendeu a dançar assim?",
2599:"Chutar e socar coisas, como você diria.",
2695:"Tenho certeza de que você já se acostumou.",
2709:"Esse cajado que você empunha...",
2710:"Onde você conseguiu isso?",
2712:"Ele se chama Bastão do Vazio.",
2734:"É aí que entra o Bastão do Vazio.",
2754:"Você sabe usar o Bastão do Vazio, não sabe?",
2861:"A ESTA ALTURA, VOCÊ JÁ ESTARIA MORTO.",
2949:"Não era isso que você desejava?",
2971:"Eu realmente admirava você...",
2974:"Que desperdício.",
3036:"Parece que você descobriu.",
3044:"Provavelmente você já se preparou para isso...",
3138:"Acho que nem você seria descarado o bastante para acreditar que conseguiria enfrentar todos de frente.",
3240:"Porque você vai se agarrar a qualquer fiapo de esperança de manter sua princesinha a salvo.",
3294:"Ver você se esforçar foi realmente magnífico.",
3296:"Como futuro imperador deste mundo desperto, eu adoraria ter você ao meu lado...!",
3316:"Você teria que ser inacreditavelmente ingênuo!",
3362:"Assim como você sempre continuou acreditando em mim...",
3390:"Então pode dar adeus a esses seus poderes mágicos de estalar os dedos e tudo mais.",
3440:"Eu vou destruir você!",
3505:"Sem isso, você nunca chegará ao fim.",
3507:"Procure o Ídolo Negro para se purificar e retornar ao lugar onde começou.",
3520:"Você viajou muito, forasteiro.",
3576:"Você me enganou!",
3650:"Você cresceu tão rápido...",
3669:"(Você realmente relaxou demais com esses livros...)",
3673:"(... Eu realmente não tenho tempo para essa bobagem.)",
3733:"Imagino que você ainda não tenha conhecido alguém com quem gostaria de copular?",
3888:"Eu protegeria você deles.",
3987:"Achei que você preferia não falar sobre isso...",
3998:"Ou você achou que eu comprei aqueles Pr***D****s só para suas costas ficarem melhores?",
4001:"Ah, falando nisso, eu devia apresentar você a um cara que conheço.",
4015:"E aí, você conseguiu algum doce?",
4057:"Só trouxemos isso de volta ao século atual.",
4085:"S-só água, obrigado.",
4110:"Você está mesmo se agarrando a qualquer esperança.",
4224:"Por acaso você já viajou?",
4258:"Mas fico feliz em saber que você conseguiu manter uma boa relação.",
4331:"Prazer em conhecer você novamente, forasteiro.",
4332:"Vejo que você está enchendo os bolsos de gafanhotos...",
4378:"[Você decidiu trocar seus gafanhotos por uma dica]",
4384:"Não se preocupe, você vai se acostumar.",
4416:"Quer se juntar a mim?",
4436:"Você bateu a cabeça ou algo assim?",
4463:"Ah, por favor, eu não estava pensando em empurrar você lá para baixo...",
4470:"Você cuidou daquelas estátuas...",
4476:"Quer se juntar a mim?",
4483:"Você realmente resolveu...!",
4484:"O que houve com esse seu cajado...",
4566:"Ou você começou a se importar com a minha opinião de repente?",
4675:"... Uma velha bruxa que se veste assim...",
4755:"E você ficou acordada a noite toda de novo?",
4799:"Não é como se eu pudesse fazer alguma coisa com você...",
4801:"Não pense que pode se esconder para sempre nesses seus ´´sonhos´´.",
4894:"Esse cajado que você empunha...",
4895:"Onde você conseguiu isso?",
4897:"Só de um baú qualquer.",
4898:"Um baú qualquer?",
4899:"Esse cajado se chama Bastão do Vazio.",
4928:"... Que você simplesmente encontrou por acaso.",
4953:"Minha existência atual é movida puramente por despeito.",
5043:"Você sempre foi bom em se convencer do contrário.",
5046:"Desista de uma vez.",
5123:"Odeio ter que contar isso a você...",
5138:"Tudo graças a este cajado que encontrei.",
5160:"E já que vou guiar você, acho que está na hora de nos apresentarmos direito.",
5193:"Não quero atrasar você...",
5227:"Você c-conseguiu descansar?",
5297:"E-então você percebeu...",
5321:"Talvez eu devesse ensinar alguns movimentos a você quando essa confusão acabar.",
5354:"Aquele castor gigante continua seguindo você!",
5375:"Parece que eles não gostam quando uso este cajado perto deles...",
5419:"Eu poderia a-apertar aquele botão para você!",
5516:"Você percebeu?",
5534:"Então você cortou o cabelo só por causa de uma moda passageira...",
5702:"Como você conseguiu este número...",
5709:"Posso ligar de volta para você?",
5717:"Você chegou a conhecer meu pai?",
5795:"Você começou a sentir minha falta enquanto eu estava fora?",
5807:"Eu simplesmente nunca fui bom o bastante para você.",
5872:"Você realmente conseguiria realizar algo assim?",
5975:"Eu deveria ter dado isto a você há algum tempo.",
6072:"Mas até uma pequena fração dos dados já conta uma história bastante reveladora.",
6096:"Posso perguntar mais uma coisa a você?",
6100:"Isso provavelmente vai parecer meio bobo para você, mas...",
6252:"Não sei nem me importo como você conseguiu chegar até aqui, mas tenho minhas ordens.",
6311:"Que bom ver você aqui em cima...",
6340:"Você parecia muito ansioso da última vez que me arrastou para essa sua confusão idiota...",
6346:"Mas eu queria dizer isso a você cara a cara.",
6349:"Você mudou, Cif.",
6411:"Mas já que meu disfarce foi descoberto, posso contar a você...",
6414:"Então vou arrancar as respostas de você na pancada.",
6416:"Adoraria ver você tentar.",
6437:"ENTÃO VOCÊ FINALMENTE DESCOBRIU...",
6581:"E pensar que você também os transformaria em seus peões.",
6654:"Por um momento, achei que você nunca conseguiria.",
6706:"Você finalmente decidiu mostrar suas cartas.",
6710:"Considerando que você nem confiou seu cajado a mim depois que desapareceu.",
6726:"Toquei num ponto sensível?",
6729:"Quando você começou a sentir pena deles?",
6765:"Desculpe por meter você nessa confusão.",
6799:"Eu vou impedir você.",
6824:"COMO VOCÊ PAROU ISSO?",
6848:"Desculpe por meter você nessa confusão.",
6851:"Pelo menos pude ver você uma última vez.",
6857:"Você realmente me seguiu até os confins do mundo...",
6877:"E agora veja o quanto você se rebaixou.",
6897:"Não que eu ache que conseguiria fazer você mudar de ideia a esta altura.",
6904:"Você conseguiu!",
6908:"Então tente aguentar firme.",
6916:"Então pare com esse melodrama e deixe eu ajudar você, seu tapado.",
6928:"Pelo menos pude ver você saudável e em segurança...",
6951:"Por que você parou?",
6977:"Acho que você bateu meu recorde!",
6981:"Acho que você não jogou tantos jogos assim...",
7012:"E assim você provará seu valor...",
7149:"E esse cajado que você está carregando...",
7169:"Agora você nunca vai me pegar, querida!",
7179:"Quero tirar uma foto sua antes de você ir!",
7278:"Eu consigo ouvir você.",
7290:"Como você me chamou...?!",
7291:"Foi você que começou!",
7311:"Então vou contar ao papai que você me chamou de pestinha.",
7324:"Não vamos avisar você de novo!",
7338:"... Ainda não encontramos a caixa-preta que você roubou.",
7360:"Por que você não deu ouvidos ao meu aviso...",
7368:"Pode mandar você de volta...",
})

# Remaining spoken-dialogue normalization. Deliberately archaic scripture and
# inscription language is intentionally excluded from this table.
corrections.update({
143:"[No entanto, a polpa é surpreendentemente doce, embora amarga]",
161:"[Só de segurar isso você já se sente desconfortável]",
209:"Apenas salte e acredite em você mesmo!",
213:"Minha memória de você.",
251:"[Mas agora que você olha mais de perto...]",
539:"E aí, gostou da reviravolta?",
661:"Por favor, coma um grilo e engasgue com ele.",
714:"Por acaso você não conhece uma saída?",
726:"Tenho certeza de que não estava ali antes; as bordas estavam limpas demais.",
823:"Você sempre começa a agir como uma criança mimada quando sabe que está perdendo.",
1031:"A batalha entre os Senhores do Vazio durou anos...",
1032:"Até que apenas três senhores permaneceram intactos...",
1112:"Cuja apatia só perde para a própria indecisão...",
1398:"Estava ficando muito chato sem você por perto.",
1446:"Você luta como uma vaca.",
1508:"Mas isso já está durando tempo demais.",
1525:"Todos sabemos que você não gosta da situação.",
1563:"Não fique no meu caminho...",
1616:"[Você diz a ela que está procurando uma jovem]",
1620:"Embora eu não possa garantir que vocês dois vão acabar no mesmo lugar.",
1628:"No entanto, duvido que estejam dispostos a compartilhar seus segredos com você.",
1760:"Uma grande cerimônia com muitos convidados, como em um conto de fadas.",
1764:"E lá estava meu futuro marido, esperando por mim no altar.",
1801:"Fique parado e espere seis segundos...",
1833:"Você provavelmente se arrependeria...",
1941:"Mas, para facilitar as coisas para você...",
1962:"G: Vou dar três turnos a você.",
2000:"Eu estava começando a me preocupar porque meus convidados não apareciam.",
2045:"[O homem não demonstra interesse em você]",
2106:"Este foi um longo dia para você.",
2167:"Mesmo assim, você demorou, quase como se estivesse brincando com eles.",
2203:"Oh, não tinha notado você aí.",
2209:"Você se importaria se eu desse uma olhada melhor?",
2219:"Você não consegue encontrar no coração um pouco de perdão para mim?",
2421:"Acho que você não entende o que esse ditado significa.",
2426:"Ou seus chifres gordos roubaram todo o senso de humor que ainda restava?",
2428:"Você não tinha nenhum para começar!",
2457:"Eu não tenho medo de você.",
2461:"[... Ela olha discretamente para você, mas logo desvia os olhos]",
2567:"E coloque sua mão esquerda no meu ombro, assim...",
2609:"E, ainda assim...",
2650:"[Uma cabeça gigante está diante de você, bloqueando seu caminho]",
2704:"Tudo o que resta para você fazer...",
2738:"... Onde o caminho para a condenação repousa dentro de ti...",
2776:"Achei que você já tivesse desistido...",
2794:"Essa espada que você carrega...",
2815:"Então também seria melhor para você...",
2857:"A morte seria gentil demais para alguém que entrega nossos segredos tão livremente.",
2864:"No fim, talvez você até desejasse estar morto.",
2955:"Afinal, ela é só uma ingênua mimada...",
2967:"Certamente você entende o que aconteceria...!",
3000:"Você está no meu caminho.",
3018:"Você continua ficando no meu caminho...",
3054:"Eu acredito em você.",
3162:"A cerimônia já começou.",
3229:"Explicar tudo em detalhes seria complicado demais para você.",
3239:"... E por que eu confiaria em você de novo?",
3268:"Umm, é ´´Senhor´´ Bee para você...",
3301:"(Só posso rezar pela segurança da Lily com você... No além...)",
3347:"Encontre a gente no fim do Vazio.",
3363:"Agora vou depositar minha fé em você.",
3375:"Está na hora de fazer jus ao meu apelido...!",
3403:"Não guardo rancor de você, da sua princesa ou do seu país!",
3588:"Esta escolha foi feita para você.",
3661:"(A geladeira começou a cheirar mal...)",
3687:"(Melhor começar a procurar.)",
3714:"Na verdade, acho que ouvi histórias sobre você quando era bem mais nova.",
3804:"Além disso, há espaço de sobra para você e sua filha.",
3811:"Por favor, pense nisso enquanto isso.",
3854:"Cheias de gratidão, as pessoas começaram a rezar para as estrelas.",
3892:"... Que tal eu ler para você da próxima vez?",
3956:"Não, deixei o Kalle cuidando disso.",
4113:"Mas, embora ela tenha me contado bastante sobre você...",
4121:"A Freya me contou que você trabalha na indústria da moda?",
4151:"Mas depois de tudo que Freya contou sobre você...",
4156:"Por que você não me conta algo sobre si mesmo?",
4157:"Ouvi dizer que você trabalha na universidade.",
4186:"É estranho, mas por um momento achei que havia algo diferente em você...",
4191:"Você se importaria se eu perguntasse uma coisa?",
4198:"Você tinha dois?",
4220:"Mas, olhando para trás, acho que eu estava focado demais no meu trabalho.",
4223:"Espero conhecer alguém que queira vir junto antes de eu ficar velho demais.",
4238:"Além disso, comparado a você, eu tive vida fácil.",
4247:"Receio ser antiquado demais para simplesmente deixar isso passar.",
4307:"Esses gafanhotos têm pouca utilidade para você.",
4320:"Tente guardar isso para você.",
4413:"No começo, você parecia meio familiar...",
4552:"Você está pisando em gelo fino demais para dar conselhos agora.",
4587:"O que aqueles garotos disseram sobre você, como chamaram você...",
4667:"Acho que começamos com o pé esquerdo.",
4689:"Mas ficar aí deitado não vai levar você a lugar nenhum.",
4768:"Na verdade, conversamos sobre isso ontem à noite e começamos a planejar nossa viagem.",
4772:"Os exames de admissão já são difíceis o bastante...",
4775:"Especialmente porque seu serviço militar começa no ano que vem...",
4786:"Agora quero que você pense no seu futuro.",
4874:"Se eu conseguir me livrar de você desse jeito...",
5045:"O que você está fazendo aqui?",
5155:"Só não fique no meu caminho.",
5361:"Mas, se ele escapar, vai estar atrás de mim num instante.",
5398:"Aquele perseguidor se move exatamente como você!",
5549:"Não suporto ver você assim.",
5658:"Mas, no fim, não há o que fazer.",
5750:"Você já tinha se tornado um bebê perfeitamente saudável.",
5774:"Mas eu sei que Gray sempre cuidou de você como se fosse da própria família.",
5805:"Estou começando a lembrar por que fui embora.",
5981:"Eu encontrei isso no meu quarto e achei que era para mim.",
5986:"Achei que ela tivesse deixado isso para você.",
6065:"Infelizmente, nem eu consigo acessar as verdadeiras profundezas deste complexo, então os detalhes continuam obscuros.",
6068:"E provavelmente nunca mais fará isso.",
6070:"No entanto, consegui acessar algumas unidades remotas de memória.",
6074:"Ainda mais curioso é o fato de todos esses registros terminarem abruptamente no mesmo ponto no tempo.",
6078:"Ou talvez uma guerra tenha começado?",
6089:"Deve ter sido difícil para você e suas irmãs durante todos esses anos...",
6102:"Acho que estamos no mesmo barco.",
6161:"Não estou atrás de você.",
6310:"Não tinha notado você aí...",
6313:"Sei que é um tiro no escuro, mas...",
6365:"Já que a cabeça deles estava sempre enfiada no rabo de Lev.",
6769:"Fale por você!",
6855:"Fale por você!",
6890:"Cuidar de você...",
6924:"A vida teria sido bem chata sem você por perto.",
6935:"Se ela estava disposta a acreditar em você, eu também estou!",
6965:"Eu acredito em você.",
6983:"Obrigado por compartilhar suas memórias comigo, Lillie.",
7050:"Que a lâmina do início corte as sanguessugas...",
7067:"Siga-me para o Vazio e você retornará ao lugar onde começou...",
7072:"Confie em si mesmo.",
7075:"Eu acredito em você.",
7104:"Este pode ser caro demais, até para você!",
7208:"Mas, caso você tenha entrado aqui por acidente antes de terminar o jogo...",
7214:"Nesta zona de fantasia, você encontrará todo tipo de coisa que, por um motivo ou outro, não entrou no jogo final.",
7226:"Olhando para trás, certamente há coisas no design dela que eu gostaria de melhorar, especialmente agora que sei como a história termina...",
7239:"Mesmo no jogo final, os sprites pequenos dos personagens tendem a ficar visualmente carregados demais.",
7249:"Há oito inimigos comuns no jogo final.",
7267:"Ao fim de nossa longa jornada.",
7276:"O fato de você ter chegado até aqui significa que sente a mesma saudade que eu.",
7319:"Afaste-se do console!",
7357:"Aquilo que você procura...",
})

# Last conversational second-person forms and visible English honorifics.
corrections.update({
1300:"Senhora Gray!",
1308:"Cuide da princesa, Senhora Gray...",
1309:"Perdoe-me, Senhora Gray.",
1371:"Bruxa!",
1408:"‘’A Senhora Gray vai ficar muito brava comigo se você não obedecer!’’",
1516:"Isso deve lembrar sua casa, Senhora Gray?",
1932:"Senhora Gray!",
2137:"Falando nisso, as coisas talvez não tivessem terminado tão bem hoje sem sua contribuição, Senhora Gray.",
2142:"Posso dizer que você não é uma senhora comum, Senhora Gray.",
2155:"Tenha uma boa noite, Senhora Gray.",
2362:"Você não vai se juntar a eles lá embaixo, Senhora Gray?",
2368:"Por favor, junte-se a eles lá embaixo, Senhora Gray.",
2370:"Senhora Gray, é um prazer vê-la.",
2379:"Senhora Gray!",
2938:"Por que me chamou aqui, Senhora Gray?",
2962:"Eu claramente julguei você mal, Senhora Gray.",
3155:"Senhora Gray!",
3167:"Por favor, Senhora Gray, salve Sua Alteza e escape!",
3180:"Senhora Gray!",
3285:"Chaaato.",
3965:"Você ficaria bem com isso?",
4052:"Você realmente não usa maquiagem há séculos, não é?",
4861:"Você me acordou só para isso?",
4863:"Eu estava pensando se você poderia se mexer só um pouquinho.",
5008:"Qual é o seu nome?",
5015:"Está procurando alguma coisa?",
5031:"Gostou do meu vestido?",
5136:"Você conhece m-magia?",
5914:"Você percebe...",
6150:"Você sente...",
6455:"IRMÃÃÃÃÃÃ!!!",
6458:"Você não entende!",
6492:"Você não gostou?",
6801:"Você não me deixa escolha.",
7253:"Tenho certeza de que você conhece o clima.",
7289:"Bruxa!",
7336:"Por que você não atira logo em mim?",
})

# Final high-confidence Brazilian lexical cleanup.
corrections.update({
    1511: "E já ouviu o apelido que deram a ela?!",
    1920: "E esse apelido pomposo... Acho que vou vomitar.",
    2146: "Fiz o meu melhor para deixar esse apelido para trás, junto com os meus feitos passados.",
    5343: "Brega demais para o seu gosto?",
    5900: "Acho sofisticado demais para o meu gosto.",
    5959: "Isto já está estranho demais!",
    6912: "Ou você planejava enfrentar o Lev sozinho?",
    7297: "Mas há muitos demais!",
    7310: "Está ficando tarde demais para isso...",
})

# Brazilian Portuguese cohesion / character-gender pass (v1.3 follow-up).
corrections.update({
    107: 'Especialmente agora que está morta.',
    108: 'Me diga.',
    182: 'Tome um pouco quando bater o desânimo.',
    183: 'E, por favor, não conte para minha irmã.',
    700: 'Por favor, não me mate!',
    716: 'E eu achando que você parecia tão capaz.',
    717: 'Sério, não me deixe esperando desse jeito.',
    826: 'Como quiser.',
    1013: 'Me diga a verdade.',
    1087: 'Não olhe diretamente nos olhos do senhor cobiçoso, costumavam dizer...',
    1153: 'Não se preocupe...',
    1166: 'Você é minha pequena portadora da luz.',
    1179: 'Não se preocupe, já foi esculpida...',
    1359: 'Cai fora, bruxa!',
    1392: 'Devo ter pegado leve com você, Alteza.',
    1393: 'Que bom ver você tão animada.',
    1394: 'Cala a boca.',
    1397: 'Obrigada.',
    1419: 'Não estou interessada.',
    1426: 'Ou talvez você simplesmente não queira ir comigo, é isso?',
    1437: 'Vem aqui, sua bobona.',
    1489: 'Antes que você possa sair...',
    1570: 'Faça como quiser...',
    1611: 'Minha balança diz que você não é uma alma perdida comum.',
    1664: 'Agradeço.',
    1695: '[Você se sente envergonhada]',
    1697: 'Você é tão pequena que fica difícil conversar se não chegar mais perto.',
    1731: 'E nem me faça começar a falar dessas coisas menores!',
    1743: 'Faz um favor e me deixa em paz, sua aberração.',
    1772: 'Por favor, me diga.',
    1777: 'Por favor, não me deixe aqui.',
    1793: 'Me deixa em paz!',
    1803: 'Não pergunte como eu sei...',
    1806: 'Agradeço sua confiança...',
    1902: 'Não tente me enganar.',
    1946: 'Não ache que esse rostinho bonito vai salvar você.',
    1978: 'Poupe suas reflexões e me diga quem mandou você.',
    1985: 'Então faça como quiser.',
    2039: '[Há muito pouco que você possa fazer para ajudá-lo.]',
    2129: 'Ouvi dizer que você era bem pé no chão.',
    2130: 'Embora eu não esperasse que você ainda se jogasse sozinha numa batalha.',
    2131: 'Um bom governante faz tudo ao seu alcance para consertar o que está errado.',
    2138: 'Pelo que entendi, você segurou aqueles bandidos sozinha por um bom tempo.',
    2140: 'E até mais do que isso, eu diria.',
    2166: 'Não dê atenção às minhas divagações.',
    2210: 'Não se preocupe, sou especialista em lidar com coisas assim.',
    2249: 'Me deixa recuperar o fôlego por um momento.',
    2302: 'Só me diz se fica bom em mim!',
    2336: 'Ele está esperando lá embaixo!',
    2458: 'Me deixa em paz.',
    2465: 'Me deixa em paz de uma vez...',
    2513: 'Não me diga que você não preparou nenhum tipo de declaração.',
    2556: 'Se você tivesse demonstrado tanto interesse quando era mais jovem, não estaríamos com tanta pressa.',
    2568: 'Agora, vem comigo e tenta relaxar.',
    2607: 'Não se preocupe, Gray.',
    2664: 'Mas talvez dê para perceber que eu não vou sair daqui tão cedo.',
    2665: 'Me deixa morrer.',
    2674: 'Se você pular num buraco bem na frente dele...',
    2689: 'Continuaram implorando por comida até eu ceder, e agora ficam por perto esperando mais...',
    2690: 'São do pior tipo, se quer saber...',
    2691: 'Não me olhe assim.',
    2758: 'Como quiser.',
    2769: 'Se você pular num buraco bem na frente dele...',
    2861: 'A ESTA ALTURA, VOCÊ JÁ ESTARIA MORTA.',
    2864: 'No fim, talvez você até desejasse estar morta.',
    2916: 'Espero que você não esteja tentando inventar alguma gracinha, espertinha.',
    2973: 'Eu sabia que você era excepcional...',
    3052: 'Só não seja tão dura consigo mesma.',
    3145: 'Vou fazer o que você quiser.',
    3146: 'Só não machuque a Gray.',
    3178: 'Rápido, peguem ela, seus idiotas!',
    3181: 'Não se preocupe!',
    3252: 'Nem pense nisso!',
    3254: 'A Gray que eu conheço não é tão medrosa!',
    3272: 'Faça como quiser.',
    3310: 'Só quero que deixe a Gray em paz!',
    3360: 'Mas enquanto você ficar aí...',
    3436: 'Vá embora!',
    3450: 'Não me faça rir!',
    3539: 'Só por uma demonstração dessas, a DIS já está disposta a fazer um contrato com você.',
    3550: 'Talvez nunca mais volte aqui.',
    3557: 'O que você está esperando?',
    3579: 'Deixem que eu fale diretamente com eles!',
    3600: 'Não se preocupe, o descanso dela é tranquilo.',
    3654: 'Ela ainda está esperando...',
    3750: 'Seja lá o que você estiver procurando...',
    3753: 'Valeu, eu acho.',
    3755: 'Cuide-se, pequena.',
    3813: 'Alô, aqui é a Gray.',
    3881: 'É muito importante que você se lembre disso.',
    3928: 'O único e verdadeiro, direto da fábrica.',
    3933: 'Agradeço, de verdade.',
    3934: 'O trabalho de escritório está acabando com as minhas costas...',
    3944: 'Que roupa fofa.',
    3954: 'Sua carona está esperando.',
    4010: '... Eu acabei de convencer a inabalável Gray a sair comigo?',
    4079: 'Você deve ser a Gray, certo?',
    4085: 'S-só água, obrigada.',
    4087: '(Estou tão nervosa...?)',
    4095: 'Não se preocupe com isso!',
    4138: 'Não se preocupe, não levei aquilo tão a sério.',
    4168: 'Parece bem sofisticado pra mim.',
    4184: 'Não, não precisa ficar assim.',
    4235: 'Não há nada de errado nisso, se quer saber.',
    4248: 'Sem problema.',
    4372: 'Se você entregar todos os seus gafanhotos, eu dou uma pista de como encontrar um deles!',
    4414: 'Mas agora que estou olhando melhor, você até que é uma gracinha...',
    4429: 'Ei, garota...',
    4437: '... A Gray não mandou você atrás de mim?',
    4446: 'Eu realmente não sei nada sobre mercenários nem sobre essas outras coisas que você está falando...',
    4447: 'Mas foi a Gray que me ensinou a me virar.',
    4462: 'Por favor, não me olhe assim.',
    4488: 'Te peguei...',
    4494: 'Dá pra ver que a Gray treinou você bem.',
    4570: 'E quero que seja de verdade também.',
    4597: 'Não diga isso, querida...',
    4655: 'Me deixa em paz.',
    4769: 'Não se preocupe, já economizei um pouco para você não precisar pagar...',
    4905: 'Não tenho interesse.',
    4908: 'Não tem interesse?!',
    4915: 'Achei que você tinha alguma devoção.',
    4941: 'Não me faça rir.',
    4961: 'Não diga isso...',
    5033: 'Que gracinha!',
    5037: 'Já está ficando cansada?',
    5049: 'Não me olhe assim.',
    5053: 'Vai embora.',
    5100: '(Outra humana?)',
    5104: 'T-tão bonita...',
    5109: 'Eu não devia ter falado isso em voz alta...',
    5120: 'Afinal, o que você estava fazendo aqui?',
    5142: 'Me leva!',
    5145: 'Por favor, me leva com você!',
    5156: 'Obrigada!',
    5157: 'Muito obrigada.',
    5158: 'Prometo que não vou atrapalhar você.',
    5192: 'Eu me viro, obrigada.',
    5198: 'Obrigada.',
    5231: 'Imagino que ainda não tenha tido nenhuma ideia brilhante?',
    5255: 'Minha mente é como uma l-lousa em branco.',
    5256: 'Você parece tensa.',
    5259: 'Não se preocupe, eu cuido de você.',
    5260: '... Obrigada, Lillie.',
    5264: '[Se agir rápido...]',
    5286: 'Então não fique pensando no pior ainda.',
    5325: 'Quem sabe, talvez você tenha talento natural por trás dessa franja.',
    5335: 'Obrigada, Lillie.',
    5336: 'Posso ficar de olho, se você estiver c-cansada.',
    5348: 'Provavelmente seria bem mais fácil sem companhia...',
    5350: 'Valeu por jogar sal na ferida.',
    5367: 'Pelo menos não parece ter interesse em você.',
    5407: 'Talvez você devesse dar um bom empurrão naquelas estátuas?',
    5409: 'E eu achando que você era só uma bobona.',
    5414: 'Estou bem, o-obrigada.',
    5418: 'Se precisar de ajuda...',
    5506: 'Não se preocupe com ela.',
    5521: 'Você deixa o cabelo crescer desde pequena!',
    5713: 'Como você e a Gray se conheceram?',
    5720: 'Por favor, me diga.',
    5730: '... Aquela mulher era a Gray?',
    5725: 'Naquela época, eu mal dormia.',
    5744: 'Mas lá estava você, Lillie.',
    5764: 'A Gray não falou deles pra você?',
    5770: 'A Gray não admitiria, mas dava para ver que aquilo abriu feridas muito mais profundas do que as da pele dela.',
    5854: 'Mesmo assim, não podemos deixar você ficar aqui.',
    5965: 'Que fofura!',
    5966: 'Foi a Gray que tirou estas?',
    6006: 'Não se preocupe.',
    6095: 'Antes de ir...',
    6097: 'Por que você se interessava tanto pela princesa?',
    6168: 'Não se preocupe com isso.',
    6320: 'Só responda minha pergunta e eu deixo você em paz.',
    6321: 'Viu Bee?',
    6323: 'Não vejo Bee há algum tempo.',
    6331: 'Não pode simplesmente pular para o próximo Brane por conta própria, espertinha?',
    6332: 'Só Add tinha poder para fazer isso.',
    6369: 'Não se preocupe com isso.',
    6413: 'Não, obrigada.',
    6417: 'Não me lembro de você ter lutado muito da outra vez.',
    6419: 'Achou que eu estava levando aquilo a sério naquela época?',
    6568: 'Mas não ache que vou pegar leve com você por sentimentalismo.',
    6593: 'Não consegui brilhar tanto quanto você.',
    6597: 'Agradeço pelas boas lembranças.',
    6601: 'Não se preocupe.',
    6680: 'Desculpe pelo transtorno.',
    6682: 'Há duas coisas que gostaria de dizer.',
    6683: 'Agradeço.',
    6685: 'Morra.',
    6762: 'Você é a Gray, certo?',
    6763: 'Embora você pareça diferente...',
    6833: 'NÃO ME DIGA.',
    6870: 'Gray, ou quem quer que você realmente seja...',
    6871: 'Você passou por muita coisa, não foi?',
    6872: 'Quaisquer que tenham sido os seus motivos...',
    6873: 'Agradeço por ter ficado ao meu lado esse tempo todo.',
    6875: 'Vamos, lado a lado!',
    6886: 'Enquanto eu esperava a Gray...',
    6898: 'Quando estiver pronta...',
    6912: 'Ou você planejava enfrentar Lev sozinha?',
    6929: 'Tenho certeza de que a Gray ficaria feliz.',
    6978: 'Podemos tentar outra coisa, se quiser.',
    6983: 'Agradeço por compartilhar suas memórias comigo, Lillie.',
    7045: 'Você sempre esteve lá...',
    7094: 'Isso não pode estar acontecendo...',
    7097: 'Mas que diabos?!',
    7099: 'Agradeço.',
    7102: 'Receio que esse já esteja em uso, pequena.',
    7103: 'Consiga o seu, barata.',
    7105: 'Só me deixa em paz...',
    7131: 'Você fez o que precisava fazer...',
    7144: 'Espero que você saiba o que está fazendo.',
    7176: 'Eu cuido das coisas aqui, então não se preocupe e aproveite um pouco.',
    7207: 'Imagino que você já saiba o que está acontecendo.',
    7279: 'Espero que tenha se divertido.',
    7283: 'Sua bobona...!',
    7314: 'Vem aqui, sua bobona.',
    7326: 'Não me faça rir.',
})

# Playable-protagonist gender consistency follow-up.
corrections.update({
    41: 'Está pronta?',
    241: '(Sua idiota completa...)',
    526: 'Todo mundo viu, sua idiota.',
    605: 'Continue sua jornada, forasteira.',
    610: 'Continue sua jornada, forasteira.',
    651: 'Ídolos não são petisco para passar o tempo, sua idiota.',
    1560: 'Você de novo, forasteira...',
    1567: 'E você, forasteira...',
    1597: 'Desculpe por arrastar você comigo, forasteira...',
    2319: 'Pensando bem, você tem agido de forma meio estranha desde então.',
    2842: 'Agradeço, forasteira.',
    2905: 'Está preocupada que não sirva mais?',
    3053: 'Mesmo quando as respostas escapam de você e está pronta para sucumbir ao desespero...',
    3520: 'Você chegou longe, forasteira.',
    3586: 'Isso não é algo com que você deva se preocupar, forasteira.',
    3608: 'Vou perguntar mais uma vez, forasteira.',
    4331: 'Prazer em reencontrar você, forasteira.',
    4902: 'Não sei bem como uma mera mortal como você consegue empunhá-lo...',
    5877: 'Respostas a essas perguntas não teriam sentido para você, forasteira.',
    6194: 'Parece preocupada.',
    6340: 'Você parecia muito ansiosa da última vez que me arrastou para essa sua confusão idiota...',
    6900: 'Está pronta?',
    7003: 'Está mesmo pronta...',
})

# Additional Brazilian Portuguese naturalness follow-up.
corrections.update({
    523: 'Com certeza eu não teria saco para fazer isso.',
    644: 'Nossa defesa não saberia disso, saberia?',
    702: 'Você não é uma daquelas coisas, né?',
    1569: 'Você não sabe quando desistir, né?',
    2908: 'Você não me viu usando isso depois dos ajustes, né?',
    3031: 'Não vou chegar a lugar nenhum assim.',
    3133: 'Não queremos estragar o clima do casamento nem da coroação, queremos?',
    3571: 'Que alma deseja levar com você?',
    3623: 'Me aconselharam a não falar com você...',
    3950: 'Minha fantasia foi comprada num supermercado...',
    4797: 'Você não foi convidada, né?',
    5427: 'Não consigo chegar à saída sem ativar aqueles painéis do chão...',
    5799: 'Você ainda está brava por causa do cabelo, né?',
    5856: 'A DIS está disposta a fazer um contrato com você.',
    6326: 'Valeu mesmo assim.',
    6735: 'Procurei por todo lado, mas não consigo encontrar o primeiro estado de memória.',
    6888: 'Ela não vem, né?',
    7204: 'Você não sai tanto assim, né?',
})

# Translation-only changes; preserve exact line indexes.
lines = PT.read_text(encoding="utf-8-sig").splitlines()
en_lines = EN.read_text(encoding="utf-8-sig").splitlines()
if len(lines) != len(en_lines):
    raise SystemExit(f"Line count mismatch PT={len(lines)} EN={len(en_lines)}")
if not BACKUP.exists():
    shutil.copy2(PT, BACKUP)

# Idempotent: each originally missing line may still be blank or may already
# contain exactly the reviewed PT-BR text from a previous run.
conflicts = [i for i,text in missing.items() if lines[i-1].strip() and lines[i-1] != text]
if conflicts:
    raise SystemExit(f"Reviewed missing-entry conflicts at indexes: {conflicts[:20]}")
for line_no, text in missing.items():
    lines[line_no - 1] = text
for line_no, text in corrections.items():
    lines[line_no - 1] = text
for old, new in GLOBAL_REPLACEMENTS:
    lines = [line.replace(old, new) for line in lines]

# Word-boundary replacements: never rewrite the "partilhar" substring inside
# an already-correct "compartilhar". This makes repeated revision runs stable.
_PTBR_WORD_REPLACEMENTS = {
    r"\bpartilhar\b": "compartilhar",
    r"\bpartilhada\b": "compartilhada",
    r"\bpartilhado\b": "compartilhado",
    r"\bpartilhadas\b": "compartilhadas",
    r"\bpartilhados\b": "compartilhados",
}
for pattern, replacement in _PTBR_WORD_REPLACEMENTS.items():
    lines = [re.sub(pattern, replacement, line, flags=re.IGNORECASE) for line in lines]

# Repair any residue written by older non-idempotent versions of this script.
while any("comcompartilhar" in line for line in lines):
    lines = [line.replace("comcompartilhar", "compartilhar") for line in lines]
# Normalize standalone honorifics that survived older translation revisions.
lines = [line.replace("Lorde ", "Senhor ").replace("Lord ", "Senhor ") for line in lines]

# Narrative brackets carry semantic/display information. Preserve them wherever
# the English localization uses them and PT-BR already has a non-empty entry.
for idx, src in enumerate(en_lines):
    s = src.strip()
    if s.startswith('[') and s.endswith(']') and lines[idx].strip():
        t = lines[idx].strip()
        if not (t.startswith('[') and t.endswith(']')):
            lines[idx] = '[' + t + ']'

PT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f"updated {PT}")
print(f"filled={len(missing)} explicit_corrections={len(corrections)} lines={len(lines)}")
